//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_RemoteController : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean PowerBtn
        {
            get
            {
                return SteamVR_Actions.remoteController_PowerBtn;
            }
        }
        
        public virtual SteamVR_Action_Boolean ChannelNext
        {
            get
            {
                return SteamVR_Actions.remoteController_ChannelNext;
            }
        }
        
        public virtual SteamVR_Action_Boolean ChannelPrev
        {
            get
            {
                return SteamVR_Actions.remoteController_ChannelPrev;
            }
        }
        
        public virtual SteamVR_Action_Boolean VolumeUp
        {
            get
            {
                return SteamVR_Actions.remoteController_VolumeUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean VolumeDown
        {
            get
            {
                return SteamVR_Actions.remoteController_VolumeDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean Speed
        {
            get
            {
                return SteamVR_Actions.remoteController_Speed;
            }
        }
    }
}
